const translations={
ms:{
notice:"Laman ini ialah platform pendidikan dan pembangunan jenama. Produk yang dipaparkan belum ditawarkan untuk jualan sehingga status regulatori disahkan.",
navHome:"Utama",navStory:"Kisah Kami",navProducts:"Produk Konsep",navLearn:"Belajar",navRoadmap:"Langkah Kami",navContact:"Hubungi",
eyebrow:"TGPU NATURALS • INISIATIF KELUARGA",heroTitle:"Warisan keluarga, diteruskan melalui ilmu dan alam.",heroLead:"Kami bermula kecil — berkongsi pengetahuan yang jelas tentang bahan tradisional, membina identiti keluarga dengan jujur, dan menyediakan asas yang betul sebelum produk ditawarkan secara rasmi.",heroLearn:"Kenali Bahan",heroRoadmap:"Lihat Perjalanan Kami",trust1:"Pendidikan dahulu",trust2:"Tiada tuntutan perubatan",trust3:"Dibangunkan langkah demi langkah",
sameRoots:"Akar yang sama",strongerGen:"Generasi yang lebih kuat.",heritageText:"TGPU Legacy dibina daripada nilai keluarga, ilmu, amanah dan usaha untuk meninggalkan sesuatu yang bermanfaat kepada generasi seterusnya.",familyValues:"Keluarga • Ilmu • Alam • Amanah",
storyEyebrow:"DARIPADA TGPU LEGACY",storyTitle:"Satu legasi, lebih daripada satu jalan untuk memberi manfaat.",storyP1:"TGPU bermaksud Tok Guru Pulau Ubi. Nama ini membawa semangat keluarga kami untuk meneruskan nilai ilmu, khidmat dan tanggungjawab. Pendidikan kekal sebagai asas TGPU Legacy, manakala TGPU Naturals ialah cabang baharu yang meneroka pengetahuan bahan tradisional dan perusahaan keluarga secara lebih tersusun.",storyP2:"Kami tidak mahu terburu-buru. Versi pertama laman ini diwujudkan untuk memperkenalkan visi, mendidik komuniti dan merekodkan perjalanan kami secara telus sebelum sebarang produk dilancarkan secara rasmi.",educationLink:"Lawati laman pendidikan TGPU Legacy →",
productsEyebrow:"TIGA PRODUK KONSEP",productsTitle:"Bahan yang keluarga kami sudah kenal.",productsIntro:"Paparan di bawah ialah visual konsep sahaja. Nama akhir, formulasi, pembungkusan, klasifikasi dan maklumat pendaftaran akan dikemas kini selepas pengesahan sebenar.",conceptBadge:"VISUAL KONSEP",kunyitTitle:"Kunyit Hitam",kunyitDesc:"Sejenis rizom daripada keluarga kunyit yang dikenali melalui warna bahagian dalamnya yang lebih gelap. Di Asia Selatan dan Asia Tenggara, tumbuhan ini mempunyai sejarah penggunaan dalam amalan tradisional.",tongkatTitle:"Tongkat Ali",tongkatDesc:"Tumbuhan yang berasal dari Asia Tenggara dan telah lama dikenali dalam budaya herba tempatan. Maklumat di laman ini hanya menerangkan latar botani dan tradisi, bukan keberkesanan perubatan.",sachiTitle:"Sacha Inchi",sachiDesc:"Tumbuhan berbiji yang berasal dari rantau Amazon dan digunakan sebagai bahan makanan dalam pelbagai bentuk. Kategori sebenar produk kami akan ditentukan berdasarkan formulasi akhirnya.",learnIngredient:"Baca penerangan umum →",
learnEyebrow:"BELAJAR DENGAN TGPU",learnTitle:"Kenali bahan sebelum mengenali produk.",learnIntro:"Kami memisahkan pengetahuan umum daripada promosi produk. Tujuannya ialah membantu pembaca memahami asal-usul dan identiti bahan dengan lebih jelas.",whatKunyit:"Apakah Kunyit Hitam?",whatKunyitText:"Kunyit Hitam ialah tumbuhan rizom daripada genus Curcuma. Nama saintifik yang sering dikaitkan dengannya ialah Curcuma caesia. Spesies dan bahan sebenar perlu disahkan pada peringkat sumber dan formulasi.",whatTongkat:"Apakah Tongkat Ali?",whatTongkatText:"Tongkat Ali ialah Eurycoma longifolia, tumbuhan Asia Tenggara yang terkenal dalam budaya herba tempatan. Sejarah penggunaan tradisional tidak sama dengan bukti klinikal untuk sesuatu produk tertentu.",whatSachi:"Apakah Sacha Inchi?",whatSachiText:"Sacha Inchi ialah Plukenetia volubilis, tumbuhan dari kawasan tropika Amerika Selatan yang menghasilkan biji. Cara sesuatu produk diklasifikasikan bergantung pada bentuk, formulasi, ramuan dan cara ia dipasarkan.",important:"Nota penting",medicalDisclaimer:"Kandungan ini untuk tujuan pendidikan dan maklumat umum sahaja. Ia bukan nasihat perubatan, diagnosis atau rawatan, dan tidak menyatakan bahawa mana-mana produk boleh mencegah, merawat atau menyembuhkan penyakit.",
roadmapEyebrow:"MULA KECIL, BINA BETUL",roadmapTitle:"Perjalanan TGPU Naturals.",step1Title:"Identiti & laman pendidikan",step1Text:"Bina jenama, kisah keluarga, struktur maklumat dan saluran komunikasi.",step2Title:"Sahkan produk sebenar",step2Text:"Kumpul foto, formulasi, ramuan, pengilang, label dan butiran bekalan sebenar daripada keluarga.",step3Title:"Klasifikasi & keperluan regulatori",step3Text:"Tentukan kategori setiap produk dan lengkapkan pendaftaran/kelulusan yang diperlukan sebelum jualan.",step4Title:"SSM & operasi",step4Text:"Tetapkan entiti perniagaan, akaun, pembekal, polisi pelanggan dan rekod operasi yang sesuai.",step5Title:"Pelancaran rasmi",step5Text:"Gantikan visual konsep dengan produk sebenar dan aktifkan fungsi jualan hanya selepas semua perkara utama disahkan.",
statusEyebrow:"STATUS SEMASA",statusTitle:"Belum ditawarkan untuk jualan.",statusText:"TGPU Naturals sedang berada pada peringkat pembangunan. Produk konsep di laman ini tidak mewakili pembungkusan akhir dan belum dipaparkan sebagai produk berdaftar. Kami akan mengemas kini maklumat hanya selepas status produk, klasifikasi dan dokumen berkaitan disahkan.",
faqTitle:"Soalan yang mungkin keluarga & pelanggan tanya.",faq1q:"Boleh saya membuat pesanan sekarang?",faq1a:"Belum melalui laman ini. Kami sedang menyusun semula produk dan mengesahkan keperluan regulatori terlebih dahulu.",faq2q:"Adakah gambar produk ini gambar sebenar?",faq2a:"Tidak. Ia ialah visual konsep untuk membantu keluarga kami membayangkan arah jenama. Gambar sebenar akan menggantikannya kemudian.",faq3q:"Adakah TGPU Naturals memberi nasihat perubatan?",faq3a:"Tidak. Kandungan laman ini bersifat pendidikan umum dan tidak menggantikan nasihat profesional kesihatan.",faq4q:"Bagaimana saya boleh mengikuti perkembangan?",faq4a:"Hubungi kami melalui WhatsApp dan nyatakan bahawa anda mahu menerima perkembangan TGPU Naturals.",
contactEyebrow:"BERKEMBANG BERSAMA",contactTitle:"Mahu tahu perkembangan TGPU Naturals?",contactText:"Anda boleh bertanya tentang projek keluarga ini, berkongsi maklum balas atau mendaftar minat untuk menerima kemas kini apabila produk sebenar dan statusnya telah disahkan.",contactBtn:"WhatsApp TGPU Legacy",footerText:"Warisan keluarga • Ilmu • Alam • Masa depan yang lebih baik",educationShort:"Pendidikan"
},
en:{
notice:"This is an educational and brand-development platform. The displayed product concepts are not offered for sale until their regulatory status is confirmed.",
navHome:"Home",navStory:"Our Story",navProducts:"Product Concepts",navLearn:"Learn",navRoadmap:"Our Roadmap",navContact:"Contact",
eyebrow:"TGPU NATURALS • A FAMILY INITIATIVE",heroTitle:"Family heritage, continued through knowledge and nature.",heroLead:"We are starting small — sharing clear information about traditional ingredients, building our family identity with honesty, and putting the right foundations in place before any product is officially offered.",heroLearn:"Explore Ingredients",heroRoadmap:"See Our Journey",trust1:"Education first",trust2:"No medical claims",trust3:"Built step by step",
sameRoots:"Same roots",strongerGen:"Stronger generations.",heritageText:"TGPU Legacy is built on family values, knowledge, trust and the aim of leaving something beneficial for the next generation.",familyValues:"Family • Knowledge • Nature • Trust",
storyEyebrow:"FROM TGPU LEGACY",storyTitle:"One legacy, more than one way to create benefit.",storyP1:"TGPU stands for Tok Guru Pulau Ubi. The name carries our family's commitment to knowledge, service and responsibility. Education remains the foundation of TGPU Legacy, while TGPU Naturals is a new branch exploring traditional-ingredient knowledge and family enterprise in a more structured way.",storyP2:"We do not want to rush. This first version introduces the vision, educates our community and records our journey transparently before any official product launch.",educationLink:"Visit the TGPU Legacy education website →",
productsEyebrow:"THREE PRODUCT CONCEPTS",productsTitle:"Ingredients our family already knows.",productsIntro:"The visuals below are concepts only. Final names, formulation, packaging, classification and registration details will be updated after proper verification.",conceptBadge:"CONCEPT VISUAL",kunyitTitle:"Black Turmeric",kunyitDesc:"A rhizomatous plant from the turmeric family, known for its darker inner colour. In South and Southeast Asia it has a history of use within traditional practices.",tongkatTitle:"Tongkat Ali",tongkatDesc:"A plant native to Southeast Asia and long known within local herbal culture. This website only describes botanical background and tradition, not medical effectiveness.",sachiTitle:"Sacha Inchi",sachiDesc:"A seed-bearing plant originating from the Amazon region and used as a food ingredient in various forms. The final category of our product will depend on its eventual formulation.",learnIngredient:"Read the general guide →",
learnEyebrow:"LEARN WITH TGPU",learnTitle:"Know the ingredient before the product.",learnIntro:"We separate general knowledge from product promotion. Our aim is to help readers understand the origins and identity of each ingredient more clearly.",whatKunyit:"What is Black Turmeric?",whatKunyitText:"Black turmeric is a rhizomatous plant from the Curcuma genus. Curcuma caesia is a scientific name commonly associated with it. The exact species and material must be verified at sourcing and formulation stage.",whatTongkat:"What is Tongkat Ali?",whatTongkatText:"Tongkat Ali is Eurycoma longifolia, a Southeast Asian plant well known in local herbal culture. Historical traditional use is not the same as clinical evidence for a particular product.",whatSachi:"What is Sacha Inchi?",whatSachiText:"Sacha Inchi is Plukenetia volubilis, a tropical South American plant that produces seeds. How a product is classified depends on its form, formulation, ingredients and how it is marketed.",important:"Important note",medicalDisclaimer:"This content is for education and general information only. It is not medical advice, diagnosis or treatment and does not claim that any product can prevent, treat or cure disease.",
roadmapEyebrow:"START SMALL, BUILD PROPERLY",roadmapTitle:"The TGPU Naturals journey.",step1Title:"Identity & education website",step1Text:"Build the brand, family story, information structure and communication channel.",step2Title:"Verify the real products",step2Text:"Collect actual photos, formulation, ingredients, manufacturer, labels and supply details from the family.",step3Title:"Classification & regulatory requirements",step3Text:"Determine each product category and complete required registration or approvals before sale.",step4Title:"SSM & operations",step4Text:"Set up the appropriate business entity, account, suppliers, customer policies and operating records.",step5Title:"Official launch",step5Text:"Replace concept visuals with real products and activate sales only after the key requirements are confirmed.",
statusEyebrow:"CURRENT STATUS",statusTitle:"Not yet offered for sale.",statusText:"TGPU Naturals is currently in development. The concepts shown here do not represent final packaging and are not presented as registered products. Information will be updated only after product status, classification and related documentation are confirmed.",
faqTitle:"Questions family and future customers may ask.",faq1q:"Can I place an order now?",faq1a:"Not through this website yet. We are reorganising the products and confirming regulatory requirements first.",faq2q:"Are these the real product photos?",faq2a:"No. They are concept visuals to help our family explore the brand direction. Real images will replace them later.",faq3q:"Does TGPU Naturals provide medical advice?",faq3a:"No. The website provides general educational information and does not replace professional healthcare advice.",faq4q:"How can I follow the progress?",faq4a:"Contact us on WhatsApp and tell us you would like to receive TGPU Naturals updates.",
contactEyebrow:"GROW WITH US",contactTitle:"Want to follow TGPU Naturals?",contactText:"Ask about this family project, share feedback or register your interest to receive updates once the actual products and their status are confirmed.",contactBtn:"WhatsApp TGPU Legacy",footerText:"Family heritage • Knowledge • Nature • A brighter tomorrow",educationShort:"Education"
},
ar:{
notice:"هذه منصة تعليمية لتطوير العلامة. المنتجات التصورية المعروضة ليست مطروحة للبيع إلى أن يتم تأكيد وضعها التنظيمي.",
navHome:"الرئيسية",navStory:"قصتنا",navProducts:"تصورات المنتجات",navLearn:"تعلّم",navRoadmap:"خطتنا",navContact:"تواصل",
eyebrow:"TGPU NATURALS • مبادرة عائلية",heroTitle:"إرث عائلي نواصله بالمعرفة والطبيعة.",heroLead:"نبدأ بخطوات صغيرة: ننشر معلومات واضحة عن المكونات التقليدية، ونبني هوية عائلية بصدق، ونضع الأساس الصحيح قبل طرح أي منتج بصورة رسمية.",heroLearn:"تعرّف على المكونات",heroRoadmap:"شاهد رحلتنا",trust1:"التعليم أولاً",trust2:"دون ادعاءات طبية",trust3:"نبني خطوة بخطوة",
sameRoots:"الجذور نفسها",strongerGen:"وأجيال أقوى.",heritageText:"تقوم TGPU Legacy على قيم العائلة والعلم والأمانة والرغبة في ترك أثر نافع للأجيال القادمة.",familyValues:"العائلة • العلم • الطبيعة • الأمانة",
storyEyebrow:"من TGPU LEGACY",storyTitle:"إرث واحد، وطرق متعددة لصناعة النفع.",storyP1:"يرمز TGPU إلى Tok Guru Pulau Ubi. ويحمل الاسم التزام عائلتنا بالعلم والخدمة والمسؤولية. يبقى التعليم أساس TGPU Legacy، بينما تمثل TGPU Naturals فرعاً جديداً لاستكشاف المعرفة بالمكونات التقليدية والمشروع العائلي بصورة أكثر تنظيماً.",storyP2:"لا نريد التسرع. هذه النسخة الأولى تعرّف بالرؤية، وتقدّم محتوى تثقيفياً للمجتمع، وتوثق رحلتنا بشفافية قبل أي إطلاق رسمي للمنتجات.",educationLink:"زيارة موقع TGPU Legacy التعليمي ←",
productsEyebrow:"ثلاثة تصورات للمنتجات",productsTitle:"مكونات تعرفها عائلتنا منذ زمن.",productsIntro:"الصور المعروضة تصورات مبدئية فقط. سيتم تحديث الاسم النهائي والتركيبة والعبوة والتصنيف وبيانات التسجيل بعد التحقق الفعلي.",conceptBadge:"تصور مبدئي",kunyitTitle:"الكركم الأسود",kunyitDesc:"نبات جذموري من فصيلة الكركم، ويُعرف بلون داخلي أكثر قتامة. وله تاريخ من الاستخدام في الممارسات التقليدية في جنوب آسيا وجنوب شرقها.",tongkatTitle:"تونغكات علي",tongkatDesc:"نبات موطنه جنوب شرق آسيا ومعروف منذ زمن في الثقافة العشبية المحلية. يشرح هذا الموقع الخلفية النباتية والتقليدية فقط، ولا يثبت فعالية طبية.",sachiTitle:"ساشا إنشي",sachiDesc:"نبات بذري موطنه منطقة الأمازون ويستخدم كمكوّن غذائي بأشكال متعددة. أما تصنيف منتجنا النهائي فسيتحدد وفق تركيبته النهائية.",learnIngredient:"اقرأ الدليل العام ←",
learnEyebrow:"تعلّم مع TGPU",learnTitle:"تعرّف على المكوّن قبل المنتج.",learnIntro:"نفصل المعرفة العامة عن الترويج للمنتجات، بهدف مساعدة القارئ على فهم أصل كل مكوّن وهويته بصورة أوضح.",whatKunyit:"ما الكركم الأسود؟",whatKunyitText:"الكركم الأسود نبات جذموري من جنس Curcuma، ويرتبط به غالباً الاسم العلمي Curcuma caesia. ويجب التحقق من النوع والمادة الفعلية في مرحلة التوريد والتركيب.",whatTongkat:"ما تونغكات علي؟",whatTongkatText:"تونغكات علي هو Eurycoma longifolia، نبات من جنوب شرق آسيا معروف في الثقافة العشبية المحلية. ولا يساوي الاستخدام التقليدي التاريخي دليلاً سريرياً على منتج بعينه.",whatSachi:"ما ساشا إنشي؟",whatSachiText:"ساشا إنشي هو Plukenetia volubilis، نبات استوائي من أمريكا الجنوبية ينتج بذوراً. ويتوقف تصنيف أي منتج على شكله وتركيبته ومكوناته وطريقة تسويقه.",important:"ملاحظة مهمة",medicalDisclaimer:"هذا المحتوى لأغراض التعليم والمعلومات العامة فقط. ولا يمثل نصيحة أو تشخيصاً أو علاجاً طبياً، ولا يدعي أن أي منتج يمنع المرض أو يعالجه أو يشفيه.",
roadmapEyebrow:"نبدأ صغيراً ونبني بصورة صحيحة",roadmapTitle:"رحلة TGPU Naturals.",step1Title:"الهوية والموقع التعليمي",step1Text:"بناء العلامة وقصة العائلة وهيكل المعلومات وقناة التواصل.",step2Title:"التحقق من المنتجات الفعلية",step2Text:"جمع الصور الحقيقية والتركيبة والمكونات والمصنّع والملصقات وبيانات التوريد.",step3Title:"التصنيف والمتطلبات التنظيمية",step3Text:"تحديد فئة كل منتج واستكمال التسجيل أو الموافقات المطلوبة قبل البيع.",step4Title:"SSM والتشغيل",step4Text:"تحديد الكيان التجاري المناسب والحساب والموردين وسياسات العملاء والسجلات التشغيلية.",step5Title:"الإطلاق الرسمي",step5Text:"استبدال التصورات بالمنتجات الحقيقية وتفعيل البيع فقط بعد تأكيد المتطلبات الأساسية.",
statusEyebrow:"الوضع الحالي",statusTitle:"غير مطروح للبيع حالياً.",statusText:"TGPU Naturals ما زالت في مرحلة التطوير. التصورات المعروضة لا تمثل العبوة النهائية ولا تُعرض على أنها منتجات مسجلة. سنحدّث المعلومات بعد تأكيد وضع المنتجات وتصنيفها والوثائق ذات الصلة.",
faqTitle:"أسئلة قد تطرحها العائلة والعملاء مستقبلاً.",faq1q:"هل يمكنني الطلب الآن؟",faq1a:"ليس عبر هذا الموقع حالياً. نحن نعيد تنظيم المنتجات ونتحقق أولاً من المتطلبات التنظيمية.",faq2q:"هل هذه الصور حقيقية؟",faq2a:"لا. إنها تصورات أولية تساعد عائلتنا على تصور اتجاه العلامة، وستحل محلها الصور الحقيقية لاحقاً.",faq3q:"هل تقدم TGPU Naturals نصائح طبية؟",faq3a:"لا. يقدم الموقع معلومات تعليمية عامة ولا يغني عن الاستشارة الصحية المهنية.",faq4q:"كيف أتابع التطورات؟",faq4a:"تواصل معنا عبر واتساب وأخبرنا أنك ترغب في متابعة تحديثات TGPU Naturals.",
contactEyebrow:"نمُ معاً",contactTitle:"هل ترغب في متابعة TGPU Naturals؟",contactText:"يمكنك السؤال عن هذا المشروع العائلي أو مشاركة رأيك أو تسجيل اهتمامك لتلقي التحديثات بعد تأكيد المنتجات الفعلية ووضعها التنظيمي.",contactBtn:"واتساب TGPU Legacy",footerText:"إرث عائلي • علم • طبيعة • مستقبل أكثر إشراقاً",educationShort:"التعليم"
}};
const educationPages={ms:"../",en:"../en.html",ar:"../ar.html"};
const whatsappMessages={
 ms:"Assalamualaikum, saya ingin tahu perkembangan TGPU Naturals.",
 en:"Assalamualaikum, I would like to know more about the TGPU Naturals project and receive updates.",
 ar:"السلام عليكم، أود معرفة المزيد عن مشروع TGPU Naturals ومتابعة مستجداته."
};
function setLanguage(lang){
 const dict=translations[lang]||translations.ms;
 document.documentElement.lang=lang;
 document.documentElement.dir=lang==="ar"?"rtl":"ltr";
 document.querySelectorAll("[data-i18n]").forEach(el=>{const key=el.dataset.i18n;if(dict[key])el.textContent=dict[key]});
 document.querySelectorAll(".lang").forEach(b=>b.classList.toggle("active",b.dataset.lang===lang));
 const educationLink=document.getElementById("educationSiteLink");
 if(educationLink) educationLink.href=educationPages[lang]||educationPages.ms;
 const wa=document.getElementById("whatsappLink");
 if(wa) wa.href="https://wa.me/60129153527?text="+encodeURIComponent(whatsappMessages[lang]||whatsappMessages.ms);
 localStorage.setItem("tgpuNaturalsLang",lang);
}
document.querySelectorAll(".lang").forEach(btn=>btn.addEventListener("click",()=>setLanguage(btn.dataset.lang)));
const requested=new URLSearchParams(location.search).get("lang");
const saved=localStorage.getItem("tgpuNaturalsLang");
setLanguage(["ms","en","ar"].includes(requested)?requested:(saved||"ms"));
const toggle=document.getElementById("menuToggle"),nav=document.getElementById("nav");
toggle?.addEventListener("click",()=>{const open=nav.classList.toggle("open");toggle.setAttribute("aria-expanded",String(open))});
nav?.querySelectorAll("a").forEach(a=>a.addEventListener("click",()=>nav.classList.remove("open")));
const sections=[...document.querySelectorAll("main section[id]")],links=[...document.querySelectorAll(".main-nav a")];
const obs=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting){links.forEach(l=>l.classList.toggle("is-current",l.getAttribute("href")==="#"+e.target.id))}})},{rootMargin:"-45% 0px -45% 0px"});
sections.forEach(s=>obs.observe(s));
